version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "my-chat-gpt"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1rsm2df40tt41"
s3_prefix = "my-chat-gpt"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
